# Generated by Django 6.0.6 on 2026-08-03 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Study Settings', max_length=100)),
                ('bmi_threshold', models.FloatField(default=18.0, help_text='Malnutrition BMI threshold (participants below this are eligible)')),
                ('age_threshold', models.IntegerField(default=60, help_text='Elderly age threshold (participants at or above this are eligible)')),
                ('campaign_period', models.CharField(default='Jan 2025 - Mar 2025', help_text='Campaign period description', max_length=250)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('battery_charging', models.BooleanField(default=False)),
                ('synced_count', models.IntegerField(default=0)),
                ('device_user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IneligibleIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('date_enroll', models.DateField()),
                ('classification', models.CharField(default='Not Eligible', max_length=25)),
                ('classification_reason', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nikshay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_enroll', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('tb_unit', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=150)),
                ('village', models.CharField(blank=True, default='', max_length=150)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('demographic_area', models.CharField(default='Unknown', max_length=100)),
                ('height_cm', models.FloatField(default=0.0)),
                ('weight_kg', models.FloatField(default=0.0)),
                ('bmi', models.FloatField(default=0.0)),
                ('symptoms', models.TextField(default='')),
                ('risk_factors', models.TextField(default='')),
                ('hiv_status', models.CharField(default='Unknown', max_length=50)),
                ('bcg_evidence', models.CharField(default='No evidence', max_length=100)),
                ('bcg_status', models.CharField(default='No', max_length=50)),
                ('bcg_beneficiary_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bcg_scar_file', models.FileField(blank=True, null=True, upload_to='bcg_scar_records/')),
                ('bcg_record_file', models.FileField(blank=True, null=True, upload_to='bcg_records/')),
                ('cxr_record_file', models.FileField(blank=True, null=True, upload_to='cxr_records/')),
                ('questionnaire_answers', models.TextField(default='{}')),
                ('eptb_details', models.TextField(default='{}')),
                ('ptb_test_details', models.TextField(default='{}')),
                ('eligible', models.BooleanField(default=True)),
                ('eligible_bcg_campaign', models.BooleanField(default=False)),
                ('classification', models.CharField(default='Pending', max_length=25)),
                ('classification_reason', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client_app_version', models.CharField(default='1.0.0', max_length=50)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TptIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_enroll', models.DateField()),
                ('tpt_undergone', models.CharField(default='Yes', max_length=20)),
                ('tpt_status', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(default='TPT+BCG', max_length=25)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('district', models.CharField(default='Tiruvallur', max_length=100)),
                ('tb_unit', models.CharField(default='Tiruvallur TU', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='central_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
