# Generated by Django 6.0.6 on 2026-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_central_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesynclog',
            name='pending_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='campaign_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='case_finding_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='demographic_area',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='district',
            field=models.CharField(default='Tiruvallur', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='facility',
            field=models.CharField(default='Local Clinic', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='father_husband_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='gender',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='nikshay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='private_facility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='public_phi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='secondary_phone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='secondary_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='secondary_phone_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='sector',
            field=models.CharField(default='Public Sector', max_length=50),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='taluka_block',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='tb_unit',
            field=models.CharField(default='Tiruvallur TU', max_length=100),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='village',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_ben_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_ben_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_beneficiary_type_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_facility',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_facility_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_has_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_registration_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_scar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_site_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_vaccination_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_vaccine_name',
            field=models.CharField(default='BCG', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='campaign_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='case_finding_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='close_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='contact_person_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='eptb_screened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='father_husband_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='informant_designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='informant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='marital_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='match_hrg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='occupation',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='participant',
            name='past_tb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='private_facility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_screened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_facility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='public_phi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='sector',
            field=models.CharField(default='Public Sector', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='socioeconomic_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='taluka_block',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_contact_known',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_history',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_regimen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_risk_factor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_undergone',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='campaign_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='case_finding_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='demographic_area',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='district',
            field=models.CharField(default='Tiruvallur', max_length=100),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='facility',
            field=models.CharField(default='Local Clinic', max_length=100),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='father_husband_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='nikshay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='private_facility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='public_phi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='secondary_phone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='secondary_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='secondary_phone_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='sector',
            field=models.CharField(default='Public Sector', max_length=50),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='taluka_block',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tb_unit',
            field=models.CharField(default='Tiruvallur TU', max_length=100),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_contact_known',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_history',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_regimen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_risk_factor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='village',
            field=models.CharField(default='', max_length=150),
        ),
    ]
