# Generated by Django 6.0.6 on 2026-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devicesynclog_pending_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ineligibleindividual',
            name='facility',
            field=models.CharField(blank=True, default='Local Clinic', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='facility',
            field=models.CharField(blank=True, default='Local Clinic', max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='match_hrg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tptindividual',
            name='facility',
            field=models.CharField(blank=True, default='Local Clinic', max_length=100),
        ),
    ]
