# Generated by Django 6.0.6 on 2026-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_role_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_has_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_record_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_records/'),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_scar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_scar_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_scar_records/'),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='cxr_record_file',
            field=models.FileField(blank=True, null=True, upload_to='cxr_records/'),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='media_checksums',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='sync_receipt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='sync_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='media_checksums',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='participant',
            name='sync_receipt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='sync_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_has_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_record_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_records/'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_scar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_scar_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_scar_records/'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='cxr_record_file',
            field=models.FileField(blank=True, null=True, upload_to='cxr_records/'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='media_checksums',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='sync_receipt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='sync_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
