# Generated by Django 6.0.6 on 2026-07-22 08:43

from django.db import migrations

def seed_eptb_sites_and_questions(apps, schema_editor):
    EptbSite = apps.get_model('eptb', 'EptbSite')
    EptbSubQuestion = apps.get_model('eptb', 'EptbSubQuestion')

    sites_list = [
        ("lymph_node_tb", "Lymph Node TB"),
        ("pleural_tb", "Pleural TB"),
        ("pericardial_tb", "Pericardial TB"),
        ("abdominal_tb", "Abdominal TB"),
        ("spine_tb", "Spine TB"),
        ("bone_joint_tb", "Bone/Joint TB"),
        ("cns_tb", "CNS TB"),
        ("genitourinary_tb", "Genitourinary TB"),
        ("female_genital_tb", "Female Genital TB"),
        ("cutaneous_tb", "Cutaneous TB"),
        ("ocular_tb", "Ocular TB"),
    ]

    sites_dict = {}
    for idx, (code, name) in enumerate(sites_list):
        site_obj = EptbSite.objects.create(code=code, name=name, display_order=idx)
        sites_dict[code] = site_obj

    sub_qs = {
        "lymph_node_tb": [
            ("ln_swelling", "Have you noticed swelling in your neck, armpit, or groin?"),
            ("ln_redness", "Has the swelling become red?"),
            ("ln_pain", "Is the swelling painful or tender?"),
            ("ln_fluctuant", "Does the swelling feel fluctuant or soft?"),
            ("ln_discharge", "Is there any discharge from the swelling?"),
            ("ln_history", "Have you had any similar history of swelling before?"),
            ("ln_fever", "Have you had fever associated with the swelling?"),
        ],
        "spine_tb": [
            ("spine_back_pain", "Have you had localized back pain for more than 6 weeks?"),
            ("spine_pain_night", "Does the pain worsen at night?"),
            ("spine_tenderness", "Do you have local tenderness or a cold abscess near the spine?"),
            ("spine_deformity", "Have you noticed a recent spinal deformity?"),
            ("spine_neurological", "Have you developed any weakness, numbness, or neurological deficits?"),
            ("spine_girdle_pain", "Do you feel heaviness around the waist or girdle pain?"),
        ],
        "bone_joint_tb": [
            ("bj_joint_pain", "Do you have persistent pain and swelling in a joint or bone for more than 6 weeks?"),
            ("bj_one_joint", "Is only one joint involved?"),
            ("bj_sinus", "Do you have a discharging sinus?"),
            ("bj_fluctuant", "Do you have fluctuant swelling with or without inflammation?"),
            ("bj_restricted", "Is joint movement painful or restricted?"),
            ("bj_muscle_wasting", "Have you noticed muscle wasting around the affected area?"),
        ],
        "pericardial_tb": [
            ("peri_pleuritic", "Do you have pleuritic chest pain?"),
            ("peri_lying_flat", "Do you have difficulty lying down flat?"),
            ("peri_swelling", "Do you have any noticeable swelling of legs or abdomen?"),
        ],
        "cns_tb": [
            ("cns_headache", "Do you have headache?"),
            ("cns_vomiting", "Have you experienced vomiting?"),
            ("cns_sensorium", "Have you experienced altered sensorium, confusion, or drowsiness?"),
            ("cns_nerve_palsy", "Have you developed any cranial nerve palsy such as double vision or facial weakness?"),
            ("cns_limb_weakness", "Have you developed weakness in any of the limbs?"),
            ("cns_seizures", "Have you had seizures?"),
            ("cns_neck_stiffness", "Do you have neck pain or stiffness?"),
        ],
        "cutaneous_tb": [
            ("skin_ulcer", "Do you have an ulcer or discharging sinus over a lymph node, bone, or joint?"),
            ("skin_red_lesion", "Do you have a persistent reddish or reddish-brown skin lesion lasting for more than 6 months?"),
            ("skin_warty_lesion", "Do you have a warty skin lesion, persistent warty skin lesion lasting for more than 6 months?"),
            ("skin_ln_involvement", "Do you have lymph node involvement along with skin lesions?"),
        ],
        "female_genital_tb": [
            ("fg_primary_inf", "Have you experienced primary infertility?"),
            ("fg_secondary_inf", "Have you experienced secondary infertility?"),
            ("fg_pelvic_pain", "Do you have chronic lower abdominal or pelvic pain?"),
            ("fg_irregular_cycles", "Do you have irregular or scanty menstrual cycles?"),
            ("fg_amenorrhea", "Have your menstrual cycle stopped?"),
            ("fg_discharge", "Do you have abnormal vaginal discharge?"),
        ],
        "genitourinary_tb": [
            ("gu_frequent_urine", "Do pass urine frequently?"),
            ("gu_urgency", "Do you experience urgency of urination?"),
            ("gu_dysuria", "Do you have burning or pain during urination?"),
            ("gu_hematuria", "Have you noticed blood in urine for at least 2 weeks?"),
            ("gu_antibiotic_fail", "Have your urinary symptoms failed to improve with antibiotics?"),
            ("gu_scrotal_pain", "Do you have scrotal pain or swelling lasting for 2 weeks or more?"),
            ("gu_scrotal_fail", "Have your scrotal symptoms failed to improve with antibiotics?"),
            ("gu_scrotal_sinus", "Do you have discharging sinuses from the scrotum?"),
            ("gu_infertility", "Have you had history of infertility?"),
        ],
        "ocular_tb": [
            ("eye_blurred_vision", "Have you noticed blurred vision?"),
            ("eye_redness", "Do you have redness of the eye?"),
            ("eye_light_sensitivity", "Are you sensitive to light?"),
            ("eye_pain", "Do you have eye pain?"),
            ("eye_floaters", "Do you see floaters?"),
            ("eye_flashes", "Do you see flashes of light?"),
        ]
    }

    for site_code, q_list in sub_qs.items():
        site_obj = sites_dict[site_code]
        for idx, (code, label) in enumerate(q_list):
            EptbSubQuestion.objects.create(
                site=site_obj,
                code=code,
                label=label,
                display_order=idx
            )


class Migration(migrations.Migration):

    dependencies = [
        ('eptb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_eptb_sites_and_questions),
    ]
