# Generated by Django 6.0.6 on 2026-07-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('study_id', models.CharField(max_length=50, unique=True)),
                ('nikshay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('date_enroll', models.DateField()),
                ('tb_exposure', models.CharField(blank=True, max_length=20)),
                ('comorbidities', models.CharField(blank=True, max_length=50)),
                ('clinical_notes', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('Case', 'Case'), ('Control', 'Control'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('district', models.CharField(default='Tiruvallur', max_length=100)),
                ('tb_unit', models.CharField(default='Tiruvallur TU', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
