# Generated by Django 6.0.6 on 2026-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='clinical_notes',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='comorbidities',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tb_exposure',
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_evidence',
            field=models.CharField(default='No evidence', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='participant',
            name='campaign_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='close_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='district',
            field=models.CharField(default='Tiruvallur', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='facility',
            field=models.CharField(default='Local Clinic', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='height_cm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='participant',
            name='match_hrg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='past_tb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='tb_unit',
            field=models.CharField(default='Tiruvallur TU', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='weight_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='classification',
            field=models.CharField(choices=[('Case', 'Case'), ('Control', 'Control'), ('Pending', 'Pending'), ('Not Eligible', 'Not Eligible')], default='Pending', max_length=25),
        ),
    ]
