# Generated by Django 6.0.6 on 2026-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_participant_clinical_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='demographic_area',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='village',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
    ]
