# Generated by Django 6.0.6 on 2026-07-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_participant_demographic_area_participant_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='hiv_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='marital_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='occupation',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='participant',
            name='risk_factors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='socioeconomic_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='symptoms',
            field=models.TextField(default=''),
        ),
    ]
