# Generated by Django 5.2.16 on 2026-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_participant_hiv_status_participant_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='contact_person_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='father_husband_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='informant_designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='informant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='private_facility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='public_phi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='secondary_phone_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='sector',
            field=models.CharField(default='Public Sector', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='taluka_block',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
