# Generated by Django 5.2.16 on 2026-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_participant_contact_person_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ptb_screened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_facility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ptb_test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
