# Generated by Django 5.2.16 on 2026-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_participant_ptb_screened_participant_ptb_test_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ptb_test_details',
            field=models.TextField(default='{}'),
        ),
    ]
