# Generated by Django 6.0.6 on 2026-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_participant_ptb_test_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eptb_details',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='participant',
            name='eptb_screened',
            field=models.BooleanField(default=False),
        ),
    ]
