# Generated by Django 6.0.6 on 2026-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_participant_eptb_details_participant_eptb_screened'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='case_finding_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
