# Generated by Django 6.0.6 on 2026-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_participant_case_finding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
