# Generated by Django 6.0.6 on 2026-07-22 08:43

from django.db import migrations

def seed_symptoms_and_risks(apps, schema_editor):
    Symptom = apps.get_model('questions', 'Symptom')
    RiskFactor = apps.get_model('questions', 'RiskFactor')

    s_list = [
        ("asymptomatic", "Asymptomatic"),
        ("cough", "Cough for more than 2 weeks"),
        ("hemoptysis", "Coughing up blood"),
        ("fever", "Fever"),
        ("weight_loss", "Weight loss"),
        ("night_sweat", "Night sweat"),
        ("chest_pain", "Chest pain"),
        ("shortness_of_breath", "Shortness of breath"),
        ("fatigue", "Fatigue"),
        ("fail_weight", "Failure to gain weight (in children)"),
        ("decreased_activity", "Decreased activity or playfulness (in children)"),
        ("others", "Others"),
    ]

    for idx, (code, name) in enumerate(s_list):
        Symptom.objects.create(code=code, name=name, display_order=idx)

    r_list = [
        ("not_applicable", "Not Applicable", False),
        ("elderly", "Elderly (age >60 years)", True),
        ("malnourished", "Undernourished / Malnourished (BMI <18.5 kg/m2)", True),
        ("contact", "Contact of Known TB Patients", True),
        ("diabetes", "Diabetes", True),
        ("past_tb", "Past History of TB", True),
        ("hiv", "HIV / AIDS", False),
        ("immunosuppressive", "Under immunosuppressive therapy (e.g. cancer chemotherapy / steroids)", False),
        ("anti_tnf", "On anti-TNF therapy / Biologicals", False),
        ("kidney", "Kidney disease on dialysis", False),
        ("pre_transplant", "Pre-transplant candidates (organ or hematological)", False),
        ("silica", "Silica exposure/silicosis", False),
        ("abuse", "Substance abuse (alcoholic/ intravenous drug users)", False),
        ("other", "Other", False),
    ]

    for idx, (code, name, is_target) in enumerate(r_list):
        RiskFactor.objects.create(code=code, name=name, is_target_hrg=is_target, display_order=idx)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_riskfactor_symptom'),
    ]

    operations = [
        migrations.RunPython(seed_symptoms_and_risks),
    ]
