# Generated by Django 6.0.6 on 2026-07-22 09:03

from django.db import migrations

def update_to_original_options(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    Option = apps.get_model('questions', 'Option')

    # 1. Update socioeconomic_status
    try:
        q_se = Question.objects.get(code="socioeconomic_status")
        q_se.options.all().delete()
        se_options = [
            ("apl", "APL (Above Poverty Line)"),
            ("bpl", "BPL (Below Poverty Line)")
        ]
        for idx, (code, name) in enumerate(se_options):
            Option.objects.create(question=q_se, code=code, name=name, display_order=idx)
    except Question.DoesNotExist:
        pass

    # 2. Update demographic_area
    try:
        q_da = Question.objects.get(code="demographic_area")
        q_da.options.all().delete()
        da_options = [
            ("tribal_non_pvtg", "Tribal- Non Particularly Vulnerable Tribal Groups"),
            ("tribal_pvtg", "Tribal- Particularly Vulnerable Tribal Groups"),
            ("rural", "Rural"),
            ("urban", "Urban"),
            ("urban_slum", "Urban Slum")
        ]
        for idx, (code, name) in enumerate(da_options):
            Option.objects.create(question=q_da, code=code, name=name, display_order=idx)
    except Question.DoesNotExist:
        pass

    # 3. Update occupation
    try:
        q_occ = Question.objects.get(code="occupation")
        q_occ.options.all().delete()
        occ_options = [
            ("1", "1. Legislators and Senior officials"),
            ("2", "2. Corporate Manager"),
            ("3", "3. General Manager"),
            ("4", "4. Physical, mathematical and engineering science professional"),
            ("5", "5. Life sciences and health professional"),
            ("6", "6. Teaching professional"),
            ("7", "7. Other professional"),
            ("8", "8. Office Clerk"),
            ("9", "9. Customer Services Clerks"),
            ("10", "10. Personal Protective Service Providers"),
            ("11", "11. Models, Sales Persons and Demonstrators"),
            ("12", "12. Market oriented skilled agriculture and fishery workers"),
            ("13", "13. Subsistence agriculture and fishery workers"),
            ("14", "14. Extraction and building trade workers"),
            ("15", "15. Metal, Machinery and related trades workers"),
            ("16", "16. Precision, handicraft, printing and related trade workers"),
            ("17", "17. Other Craft and related trades and workers"),
            ("18", "18. Stationary Plant and related Operators"),
            ("19", "19. Machine Operators and Assembler"),
            ("20", "20. Drivers and Mobile Plant Operators"),
            ("21", "21. Sales and Services elementary occupations"),
            ("22", "22. Agriculture, fishery and related labour"),
            ("23", "23. Laborers in mining, construction, manufacturing and transport"),
            ("24", "24. New Workers seeking employment"),
            ("25", "25. Workers reporting occupation unidentifiable or inadequately"),
            ("26", "26. Workers not reporting any occupation"),
            ("27", "27. House Wife")
        ]
        for idx, (code, name) in enumerate(occ_options):
            Option.objects.create(question=q_occ, code=code, name=name, display_order=idx)
    except Question.DoesNotExist:
        pass

    # 4. Update marital_status
    try:
        q_ms = Question.objects.get(code="marital_status")
        q_ms.options.all().delete()
        ms_options = [
            ("single", "Single"),
            ("married", "Married")
        ]
        for idx, (code, name) in enumerate(ms_options):
            Option.objects.create(question=q_ms, code=code, name=name, display_order=idx)
    except Question.DoesNotExist:
        pass

    # 5. Update hiv_status
    try:
        q_hiv = Question.objects.get(code="hiv_status")
        q_hiv.options.all().delete()
        hiv_options = [
            ("positive", "Positive"),
            ("reactive", "Reactive"),
            ("negative", "Non Reactive / Negative")
        ]
        for idx, (code, name) in enumerate(hiv_options):
            Option.objects.create(question=q_hiv, code=code, name=name, display_order=idx)
    except Question.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20260722_1424'),
    ]

    operations = [
        migrations.RunPython(update_to_original_options),
    ]
