# Generated by Django 6.0.6 on 2026-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_update_options_to_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='questionnaire_answers',
            field=models.TextField(default='{}'),
        ),
    ]
