# Generated by Django 5.2.16 on 2026-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_participant_questionnaire_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eligible_bcg_campaign',
            field=models.BooleanField(default=False, verbose_name='Eligible for BCG vaccine during campaign period'),
        ),
    ]
