# Generated by Django 5.2.16 on 2026-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_participant_eligible_bcg_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bcg_eligibility_criteria',
            field=models.TextField(blank=True, null=True, verbose_name='Eligibility Criteria for Adult BCG Vaccination'),
        ),
    ]
