# Generated by Django 6.0.6 on 2026-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_participant_bcg_eligibility_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcgVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('beneficiary_gender', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ben_mobile_number', models.CharField(blank=True, default='', max_length=50)),
                ('dob', models.CharField(blank=True, default='', max_length=50)),
                ('vaccination_status', models.CharField(blank=True, default='', max_length=50)),
                ('beneficiary_type_name', models.CharField(blank=True, default='', max_length=250)),
                ('address', models.TextField(blank=True, default='')),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('date_created', models.CharField(blank=True, default='', max_length=100)),
                ('facility_id', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_beneficiary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_facility',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_status',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_vaccine_name',
            field=models.CharField(default='BCG', max_length=100),
        ),
    ]
