# Generated by Django 6.0.6 on 2026-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_bcgvaccination_approved_by_bcgvaccination_ben_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tpt_contact_known',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_history',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_regimen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tpt_undergone',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='classification',
            field=models.CharField(choices=[('Case', 'Case'), ('Control', 'Control'), ('Pending', 'Pending'), ('Not Eligible', 'Not Eligible'), ('TPT+BCG', 'TPT+BCG')], default='Pending', max_length=25),
        ),
    ]
