# Generated by Django 6.0.6 on 2026-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_tptindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tpt_risk_factor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='tpt_risk_factor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
