# Generated by Django 6.0.6 on 2026-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_ineligibleindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_has_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_record_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_records/'),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_scar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_has_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_record_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_records/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_scar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_has_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_record_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_records/'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_scar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
