# Generated by Django 6.0.6 on 2026-08-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_ineligibleindividual_bcg_has_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='cxr_record_file',
            field=models.FileField(blank=True, null=True, upload_to='cxr_records/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='cxr_record_file',
            field=models.FileField(blank=True, null=True, upload_to='cxr_records/'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='cxr_record_file',
            field=models.FileField(blank=True, null=True, upload_to='cxr_records/'),
        ),
    ]
