# Generated by Django 6.0.6 on 2026-08-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_ineligibleindividual_cxr_record_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='bcg_scar_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_scar_records/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='bcg_scar_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_scar_records/'),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='bcg_scar_file',
            field=models.FileField(blank=True, null=True, upload_to='bcg_scar_records/'),
        ),
    ]
