# Generated by Django 5.2.16 on 2026-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_ineligibleindividual_bcg_scar_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='classification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='classification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='classification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='classification',
            field=models.CharField(choices=[('Case', 'Case'), ('Control', 'Control'), ('Pending', 'Pending'), ('Not Eligible', 'Not Eligible'), ('TPT+BCG', 'TPT+BCG'), ('Excluded', 'Excluded')], default='Pending', max_length=25),
        ),
    ]
