# Generated by Django 6.0.6 on 2026-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_update_risk_factors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ineligibleindividual',
            name='match_hrg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='match_hrg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tptindividual',
            name='match_hrg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
