# Generated by Django 6.0.6 on 2026-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_userprofile_role_auditlog_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='screening_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='screening_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='screening_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ineligibleindividual',
            name='nikshay_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nikshay_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tptindividual',
            name='nikshay_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
