# Generated by Django 6.0.6 on 2026-08-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_ineligibleindividual_screening_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='reconciliation_status',
            field=models.CharField(db_index=True, default='UNRECONCILED', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='reconciliation_status',
            field=models.CharField(db_index=True, default='UNRECONCILED', max_length=50),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='reconciliation_status',
            field=models.CharField(db_index=True, default='UNRECONCILED', max_length=50),
        ),
    ]
