# Generated by Django 6.0.6 on 2026-09-03 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_ineligibleindividual_reconciliation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Nodal Officer', 'Nodal Officer'), ('Doctor', 'Doctor'), ('Project Nurse', 'Project Nurse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Nodal Officer', 'Nodal Officer'), ('Doctor', 'Doctor'), ('Project Nurse', 'Project Nurse')], default='Project Nurse', max_length=50),
        ),
        migrations.CreateModel(
            name='NikshayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikshay_id', models.CharField(db_index=True, max_length=100)),
                ('study_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('screening_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('cohort', models.CharField(choices=[('Participant', 'Participant'), ('TPT', 'TPT Individual'), ('Ineligible', 'Ineligible Individual')], default='Participant', max_length=50)),
                ('full_name', models.CharField(blank=True, default='', max_length=250)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('tb_unit', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='Personal Details Form', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nikshay_records', to=settings.AUTH_USER_MODEL)),
                ('ineligible_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikshay_records', to='questions.ineligibleindividual')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikshay_records', to='questions.participant')),
                ('tpt_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikshay_records', to='questions.tptindividual')),
            ],
            options={
                'verbose_name': 'Nikshay Record',
                'verbose_name_plural': 'Nikshay Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
