# Generated by Django 6.0.6 on 2026-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_alter_rolepermission_role_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineligibleindividual',
            name='sync_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='sync_receipt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ineligibleindividual',
            name='sync_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='sync_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='sync_receipt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='sync_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='sync_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='sync_receipt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tptindividual',
            name='sync_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
