# Generated by Django 6.0.6 on 2026-09-13 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_ineligibleindividual_sync_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tb_unit', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(default='3.4.1', max_length=50)),
                ('battery', models.IntegerField(default=100)),
                ('status', models.CharField(default='online', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Study Device',
                'verbose_name_plural': 'Study Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('tb_unit', models.CharField(db_index=True, max_length=100, unique=True)),
                ('launch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('concluding_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_study_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Site',
                'verbose_name_plural': 'Study Sites',
                'ordering': ['state', 'district', 'tb_unit'],
            },
        ),
    ]
